[package]
name = "wasmer-examples/next-ssg-wasmer-starter"
version = "0.2.0"
description = "Next.js static Website Wasmer starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/next-ssg-wasmer-starter"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "out"
